name: Test

on: [push]

jobs:
  local-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

              # Se importa la ruta para reutilizar un action dentro de otro action y automaticamente se agrega el workflow que est√° dentro de la carpeta
      - name: ls
        uses: ./.github/actions/my-action
        with:
          message: "Fernando"
        